volumes:
  db_storage:
  n8n_storage:
  redis_storage:
  evolution_storage:
  evolution_instances_storage: 
  traefic_storage:

x-logging: &common-logging
  options:
    max-size: "10m"
    max-file: "5"
    compress: "true"
  driver: json-file
  
x-n8n: &common-n8n
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
    - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
    - N8N_SECURE_COOKIE=false
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - N8N_RUNNERS_ENABLED=true    
    - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
  links:
    - redis
  volumes:
    - n8n_storage:/home/node/.n8n:1.98.1
  logging: *common-logging
  depends_on:
    redis:
      condition: service_healthy

services:

  traefik:
    image: "traefik"
    restart: always
    logging: *common-logging
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefic_storage:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    volumes:
      - redis_storage:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10
    logging: *common-logging
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}    

  evolution-api:
    container_name: evolution-api
    image: atendai/evolution-api
    restart: always
    logging: *common-logging
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=${AUTH_API_KEY}
    volumes:
      - evolution_storage:/evolution/store
      - evolution_instances_storage:/evolution/instances

  n8n:
    container_name: n8n
    <<: *common-n8n
    ports:
      - 5678:5678
#      - "127.0.0.1:5678:5678" 
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN_NAME}
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./local-files:/files
      
  n8n-worker:
    container_name: n8n-worker
    <<: *common-n8n
    # command: worker
    entrypoint: ["n8n", "worker"]
    depends_on:
      - n8n
      - evolution-api
